name: omop_simple
stages:
  - name: filter_codes
    params:
      codes_to_remove: []
      is_prefix: false

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
    skip: ${is_not_null:${vocab}}

  - name: StaticDataCollector
    agg_to: ${output_dir}/static_data.pickle
    params:
      static_code_prefixes:
        - MEDS_BIRTH

  - name: filter_codes
    params:
      codes_to_remove:
        - MEDS_BIRTH
      is_prefix: true

  - name: inject_time_intervals
    params:
      time_intervals_spec: ${time_intervals_spec}

  - name: IntervalEstimator
    params:
      time_intervals_spec: ${time_intervals_spec}
    agg_to: ${output_dir}/${intervals_fn}
    skip: ${is_not_null:${vocab}}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
